#CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.cheb --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.6 --model_indices 0 --num_edges=34277 --run_split=9 --hidden=64 --num_hops=2
#CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.cheb --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.6 --model_indices 0 --num_edges=34277 --run_split=8 --hidden=64 --num_hops=2
#CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.cheb --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.6 --model_indices 0 --num_edges=26277 --run_split=7 --hidden=64 --num_hops=2
#CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.cheb --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.6 --model_indices 0 --num_edges=42277 --run_split=6 --hidden=64 --num_hops=2
#CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.cheb --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.6 --model_indices 0 --num_edges=46277 --run_split=5 --hidden=64 --num_hops=2
#CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.cheb --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.6 --model_indices 0 --num_edges=30277 --run_split=4 --hidden=64 --num_hops=2
#CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.cheb --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.6 --model_indices 0 --num_edges=42277 --run_split=3 --hidden=64 --num_hops=2
#CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.cheb --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.6 --model_indices 0 --num_edges=46277 --run_split=2 --hidden=64 --num_hops=2
#CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.cheb --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.6 --model_indices 0 --num_edges=30277 --run_split=1 --hidden=64 --num_hops=2
#CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.cheb --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.6 --model_indices 0 --num_edges=30277 --run_split=0 --hidden=64 --num_hops=2

#CUDA_DEVICE=0 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.cheb --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.6 --model_indices 0 --num_edges=30277 --num_hops=2 --hidden=64
#CUDA_DEVICE=6 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.cheb --dataset=squirrel --rewired --rewirer_step=0.1 --dropout=0.8 --model_indices 0 --num_edges=17336 --num_hops=2 --hidden=64
CUDA_DEVICE=6 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.cheb --dataset=citeseer --rewired --rewirer_step=0.1 --dropout=0.8 --model_indices 0 --num_edges=16076 --num_hops=2 --hidden=64 --runs=10
