#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Wisconsin --lr=0.01 --step=0.1 --mode=supervised --sample_size=20 --eps=0.1 --split=0 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Wisconsin --lr=0.01 --step=0.1 --mode=supervised --sample_size=20 --eps=0.1 --split=1 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Wisconsin --lr=0.01 --step=0.1 --mode=supervised --sample_size=20 --eps=0.1 --split=2 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Wisconsin --lr=0.01 --step=0.1 --mode=supervised --sample_size=20 --eps=0.1 --split=3 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Wisconsin --lr=0.01 --step=0.1 --mode=supervised --sample_size=20 --eps=0.1 --split=4 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Wisconsin --lr=0.01 --step=0.1 --mode=supervised --sample_size=20 --eps=0.1 --split=5 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Wisconsin --lr=0.01 --step=0.1 --mode=supervised --sample_size=20 --eps=0.1 --split=6 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Wisconsin --lr=0.01 --step=0.1 --mode=supervised --sample_size=20 --eps=0.1 --split=7 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Wisconsin --lr=0.01 --step=0.1 --mode=supervised --sample_size=20 --eps=0.1 --split=8 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Wisconsin --lr=0.01 --step=0.1 --mode=supervised --sample_size=20 --eps=0.1 --split=9 --with_rand_signal
#
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Texas --lr=0.01 --step=0.2 --mode=supervised --sample_size=30 --eps=0.1 --split=0 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Texas --lr=0.01 --step=0.2 --mode=supervised --sample_size=30 --eps=0.1 --split=1 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Texas --lr=0.01 --step=0.2 --mode=supervised --sample_size=30 --eps=0.1 --split=2 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Texas --lr=0.01 --step=0.2 --mode=supervised --sample_size=30 --eps=0.1 --split=3 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Texas --lr=0.01 --step=0.2 --mode=supervised --sample_size=30 --eps=0.1 --split=4 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Texas --lr=0.01 --step=0.2 --mode=supervised --sample_size=30 --eps=0.1 --split=5 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Texas --lr=0.01 --step=0.2 --mode=supervised --sample_size=30 --eps=0.1 --split=6 --with_rand_signal
#CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Texas --lr=0.01 --step=0.2 --mode=supervised --sample_size=30 --eps=0.1 --split=7 --with_rand_signal
#CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Texas --lr=0.01 --step=0.2 --mode=supervised --sample_size=30 --eps=0.1 --split=8 --with_rand_signal
#CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Texas --lr=0.01 --step=0.2 --mode=supervised --sample_size=30 --eps=0.1 --split=9 --with_rand_signal
#
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Cornell --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=0 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Cornell --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=1 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Cornell --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=2 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Cornell --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=3 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Cornell --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=4 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Cornell --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=5 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Cornell --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=6 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Cornell --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=7 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Cornell --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=8 --with_rand_signal
#CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Cornell --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=9 --with_rand_signal

CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Chameleon --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=0 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Chameleon --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=1 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Chameleon --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=2 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Chameleon --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=3 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Chameleon --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=4 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Chameleon --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=5 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Chameleon --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=6 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Chameleon --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=7 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Chameleon --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=8 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Chameleon --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=9 --with_rand_signal

CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Squirrel --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=0 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Squirrel --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=1 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Squirrel --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=2 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Squirrel --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=3 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Squirrel --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=4 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Squirrel --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=5 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Squirrel --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=6 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Squirrel --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=7 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Squirrel --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=8 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Squirrel --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=9 --with_rand_signal

CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Actor --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=0 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Actor --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=1 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Actor --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=2 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Actor --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=3 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Actor --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=4 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Actor --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=5 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Actor --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=6 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Actor --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=7 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Actor --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=8 --with_rand_signal
CUDA_DEVICE=1 python -m models.encoder_node_classification --dataset=Actor --lr=0.01 --step=0.1 --mode=supervised --sample_size=64 --eps=0.1 --split=9 --with_rand_signal
