CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.major --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.3 --hidden=128 --model_indices 0 --num_edges=34277 --run_split=9 --epochs=1
CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.major --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.3 --hidden=128 --model_indices 0 --num_edges=34277 --run_split=8 --epochs=1
CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.major --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.3 --hidden=128 --model_indices 0 --num_edges=26277 --run_split=7 --epochs=1
CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.major --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.3 --hidden=128 --model_indices 0 --num_edges=42277 --run_split=6 --epochs=1
CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.major --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.3 --hidden=128 --model_indices 0 --num_edges=46277 --run_split=5 --epochs=1
CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.major --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.3 --hidden=128 --model_indices 0 --num_edges=30277 --run_split=4 --epochs=1
CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.major --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.3 --hidden=128 --model_indices 0 --num_edges=42277 --run_split=3 --epochs=1
CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.major --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.3 --hidden=128 --model_indices 0 --num_edges=46277 --run_split=2 --epochs=1
CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.major --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.3 --hidden=128 --model_indices 0 --num_edges=30277 --run_split=1 --epochs=1
CUDA_DEVICE=1 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.major --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.3 --hidden=128 --model_indices 0 --num_edges=30277 --run_split=0 --epochs=1

#CUDA_DEVICE=0 /data_seoul/seanl/miniconda/envs/rewire/bin/python -m benchmark.node_classification.major --dataset=chameleon --rewired --rewirer_step=0.1 --dropout=0.9 --model_indices 0 --num_edges=30277
