CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.9
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.8
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.2 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.7
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.6
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.53
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.52
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.51
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.504
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.503
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.5025
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.502
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.5015
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.501
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.5005
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.5
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.499
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.498
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.497
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.496
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.495
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.49
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.48
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.47
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.46
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.45
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.44
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.43
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.42
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.41
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.4
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.3
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.2
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0.1
CUDA_DEVICE=0 python -m models.encoder_node_classification --dataset=Cora --lr=0.01 --step=0.1 --sample_size=20 --eps=0.1 --with_rand_signal --with_node_feature --h_den=0
